SELECT CASENUMBER, CUSTOMER_COMPANY_NAME__C, DESCRIPTION, ORIGINATOR_OPEN_DATE__C, LASTMODIFIEDDATE, GSS_LAST_TOUCH_TIME__C, CLOSEDDATE, GSS_ESC_ALERT_LEVEL__C
FROM DWH_GSS_CASE  
WHERE (PRODUCTID in (SELECT id FROM DWH_GSS_PRODUCT where NAME LIKE '%SAN%' and NAME NOT like '%Beta%') or SUBJECT like '%SAN%')
and SUBJECT not like '%eForm%' and
GSS_PROBLEM_CATEGORY__C not in ('Licensing','Invoice','Renewals','Refund/Rebate','Registration') {0}